### ISSUE TITLE
Xt550-t2 rj45

### ISSUE THREAD

**Issue by lcsjandrey** [Mieze/IntelLucy#1]
Running opencore 1.0.0 on Sonoma 14.4.1. 
Card doesn't appear under pci devices or Ethernet. It works just fine on windows. 
I have switched pcie slots and no luck.

**Comment by Mieze** [comment]
Please send my your EFI folder and an IOReg dump for diagnosing the issue.

**Comment by lcsjandrey** [comment]
Awesome will do later tonight, thanks for your help! 

Also I did try with a XT540 and it recognizes both ports and it works well with 1GB but I switch the port on the router to the 10gbe, it will show as no network active. I will ad the logs  later tonight.
 
Many thanks!!!

**Comment by Mieze** [comment]
As I haven't received any of the debug information I requested, I assume that the issue has been resolved and will close the issue now.
